
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tobyspringboot
    username: oyatrij
    password: 4orescout
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
